# Generated by Django 4.2.14 on 2026-09-12 08:31

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("profession", models.CharField(blank=True, max_length=150)),
                (
                    "nid_number",
                    models.CharField(max_length=30, verbose_name="NID Number"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("general_seeker", "General Seeker"),
                            ("authority", "Found Reporter / Authority"),
                        ],
                        default="general_seeker",
                        max_length=20,
                    ),
                ),
                ("is_authority", models.BooleanField(default=False)),
                (
                    "authority_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("police", "Police"),
                            ("govt_employee", "Govt Employee"),
                            ("rab", "RAB"),
                            ("army", "Army"),
                            ("morgue_authority", "Morgue Authority"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dhaka", "Dhaka"),
                            ("chattogram", "Chattogram"),
                            ("rajshahi", "Rajshahi"),
                            ("khulna", "Khulna"),
                            ("barishal", "Barishal"),
                            ("sylhet", "Sylhet"),
                            ("rangpur", "Rangpur"),
                            ("mymensingh", "Mymensingh"),
                        ],
                        help_text="Required when authority_type is Morgue Authority",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(
                        default=apps.accounts.models.generate_otp, max_length=6
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.accounts.models.default_otp_expiry
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
