# Generated by Django 4.2.14 on 2026-09-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nid_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='NID Number'),
        ),
    ]
