# Generated by Django 4.2.14 on 2026-09-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='missing_since',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
