# Generated by Django 4.2.14 on 2026-09-12 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0003_matchresult_reviewed_at_matchresult_reviewed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='search.matchresult')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
