# Generated by Django 4.2.14 on 2026-09-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('found_persons', '0004_lostperson_embedding_generated_at_and_more'),
        ('search', '0004_matchnotification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchresult',
            unique_together={('search_query', 'found_person')},
        ),
        migrations.AddField(
            model_name='matchresult',
            name='lost_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='found_persons.lostperson'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='found_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='found_persons.foundperson'),
        ),
        migrations.AlterUniqueTogether(
            name='matchresult',
            unique_together={('search_query', 'found_person'), ('search_query', 'lost_person')},
        ),
        migrations.AddConstraint(
            model_name='matchresult',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('found_person__isnull', False), ('lost_person__isnull', True)), models.Q(('found_person__isnull', True), ('lost_person__isnull', False)), _connector='OR'), name='match_result_exactly_one_target'),
        ),
    ]
