# Generated by Django 4.2.14 on 2026-09-12 08:31

import apps.found_persons.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=apps.found_persons.models.found_photo_upload_path
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("found_alive", "Found Alive"),
                            ("unidentified_deceased", "Unidentified Deceased"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "found_location",
                    models.CharField(
                        help_text="Free-text location description", max_length=255
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("dhaka", "Dhaka"),
                            ("chattogram", "Chattogram"),
                            ("rajshahi", "Rajshahi"),
                            ("khulna", "Khulna"),
                            ("barishal", "Barishal"),
                            ("sylhet", "Sylhet"),
                            ("rangpur", "Rangpur"),
                            ("mymensingh", "Mymensingh"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "found_timestamp",
                    models.DateTimeField(help_text="When the person was found"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes: approximate age, clothing, marks, etc.",
                    ),
                ),
                ("face_embedding", models.JSONField(blank=True, null=True)),
                ("embedding_generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set False once matched/resolved or purged",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, default=apps.found_persons.models.default_expiry
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="found_person_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "found_persons",
                "ordering": ["-created_at"],
            },
        ),
    ]
