# Generated by Django 4.2.14 on 2026-09-12 11:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found_persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundperson',
            name='distinguishing_marks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('tattoo', 'Tattoo'), ('scar', 'Scar'), ('birthmark', 'Birthmark'), ('mole', 'Mole'), ('piercing', 'Piercing')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='estimated_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='status',
            field=models.CharField(choices=[('unidentified', 'Unidentified'), ('under_care', 'Under Care'), ('reunited', 'Reunited')], default='unidentified', max_length=20),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='description',
            field=models.TextField(blank=True, help_text='Additional notes: clothing, dialect, behavior, etc.'),
        ),
    ]
