# Generated by Django 4.2.14 on 2026-09-12 18:45

import apps.found_persons.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('found_persons', '0002_foundperson_distinguishing_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to=apps.found_persons.models.lost_photo_upload_path)),
                ('full_name', models.CharField(max_length=255)),
                ('last_seen_location', models.CharField(help_text='Free-text location description', max_length=255)),
                ('division', models.CharField(choices=[('dhaka', 'Dhaka'), ('chattogram', 'Chattogram'), ('rajshahi', 'Rajshahi'), ('khulna', 'Khulna'), ('barishal', 'Barishal'), ('sylhet', 'Sylhet'), ('rangpur', 'Rangpur'), ('mymensingh', 'Mymensingh')], max_length=20)),
                ('last_seen_timestamp', models.DateTimeField(help_text='When the person was last seen')),
                ('description', models.TextField(blank=True, help_text='Additional notes: clothing, health condition, etc.')),
                ('estimated_age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('distinguishing_marks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('tattoo', 'Tattoo'), ('scar', 'Scar'), ('birthmark', 'Birthmark'), ('mole', 'Mole'), ('piercing', 'Piercing')], max_length=20), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('found', 'Found')], default='missing', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Set False once reunited or withdrawn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_person_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lost_persons',
                'ordering': ['-created_at'],
            },
        ),
    ]
