# Generated by Django 4.2.14 on 2026-09-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found_persons', '0003_lostperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostperson',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostperson',
            name='face_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
